### ISSUE TITLE
IP not shown when IPv4 and IPv6 are both available

### ISSUE THREAD

**Issue by mtness** [liamstewart23/Firefox-WebsiteIP#3]
Hi there!

When IPv4 and IPv6 are available, one can't see the IP-Adress in the infobubble.

When only IPv4 is available, it is shown.
![Snap106](https://user-images.githubusercontent.com/15540/129011373-f89ed43d-216c-4185-92ed-9709f5dec3b8.png)

**Comment by liamstewart23** [comment]
Hi @mtness,

Thanks for reporting this. 

Few questions to help further investigate this report. 

- What website are you visiting to replicate this issue? 
- Are you receiving any browser console errors? 
- What version of Firefox?
- What Operating System? 

From a quick review on OSX + Latest Firefox (v91.0)

Here is the infobubble when IPv4 and IPv6 are available on https://google.ca/ 

![Screen Shot 2021-08-16 at 5 17 39 PM](https://user-images.githubusercontent.com/15363506/129630743-3fc73226-8f6b-4b7a-a1a3-2a1f2e5723f2.png)

Testing IPv6 https://ipv6.google.com/ shows:

![Screen Shot 2021-08-16 at 5 20 36 PM](https://user-images.githubusercontent.com/15363506/129631074-e981381b-f103-4b98-aa14-ad5b6ca81793.png)

Testing IPv4 on http://ipv4.tlund.se/ shows: 

![Screen Shot 2021-08-16 at 5 22 39 PM](https://user-images.githubusercontent.com/15363506/129631167-18bb4433-2be7-4e1e-99d9-2f36c813facc.png)

Can you confirm you are experiencing the same issue with the above domains.

**Comment by liamstewart23** [comment]
This issue was closed because it has been inactive for over 14 days and could not be reproduced. 

Please open another ticket and reference this one if you are having the issue still.

**Comment by mtness** [comment]
Hi there!
Sorry, I haven't seen your response until now^^

Can't repoduce it, too -
will open a new ticket if this comes back to my attention.

Best regards,
MT


> 
> 
> Hi @mtness,
> 
> Thanks for reporting this.
> 
> Few questions to help further investigate this report.
> 
>     * What website are you visiting to replicate this issue?
> 
>     * Are you receiving any browser console errors?
> 
>     * What version of Firefox?
> 
>     * What Operating System?
> 
> 
> From a quick review on OSX + Latest Firefox (v91.0)
> 
> Here is the infobubble when IPv4 and IPv6 are available on https://google.ca/
> 
> ![Screen Shot 2021-08-16 at 5 17 39 PM](https://user-images.githubusercontent.com/15363506/129630743-3fc73226-8f6b-4b7a-a1a3-2a1f2e5723f2.png)
> 
> Testing IPv6 https://ipv6.google.com/ shows:
> 
> ![Screen Shot 2021-08-16 at 5 20 36 PM](https://user-images.githubusercontent.com/15363506/129631074-e981381b-f103-4b98-aa14-ad5b6ca81793.png)
> 
> Testing IPv4 on http://ipv4.tlund.se/ shows:
> 
> ![Screen Shot 2021-08-16 at 5 22 39 PM](https://user-images.githubusercontent.com/15363506/129631167-18bb4433-2be7-4e1e-99d9-2f36c813facc.png)
> 
> Can you confirm you are experiencing the same issue with the above domains.

**Comment by liamstewart23** [comment]
Thanks!

Also noticed I supplied the wrong IPv6 screenshot for https://ipv6.google.com/.

![Screen Shot 2021-09-12 at 7 59 15 PM](https://user-images.githubusercontent.com/15363506/133006967-0a33e40d-bd9d-4d8f-980f-45328f31c3cc.png)
